#cloud-config
package_update: true
package_upgrade: true
timezone: "America/Sao_Paulo"

packages:
  - mariadb-server

write_files:
  # SSH - Altera a porta de 22 para 2222
  - path: /etc/ssh/sshd_config.d/port-override.conf
    permissions: "0644"
    content: |
      Port 2222
      PasswordAuthentication no
      PermitRootLogin no

  # Configurar o MariaDB para aceitar conexoes internas
  - path: /etc/mysql/mariadb.conf.d/50-server.cnf
    permissions: '0644'
    content: |
      [server]
      user                    = mysql
      pid-file                = /run/mysqld/mysqld.pid
      socket                  = /run/mysqld/mysqld.sock
      basedir                 = /usr
      datadir                 = /var/lib/mysql
      lc_messages_dir         = /usr/share/mysql
      lc_messages             = en_US
      bind-address            = 0.0.0.0
      max_connections         = 200
      character-set-server    = utf8mb4
      collation-server        = utf8mb4_unicode_ci

runcmd:
  - systemctl enable --now mariadb
  - mysql -e "CREATE DATABASE IF NOT EXISTS \`${db_name}\` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;"
  - mysql -e "CREATE USER IF NOT EXISTS '${db_user}'@'${server01_private_ip}' IDENTIFIED BY '${db_password}';"
  - mysql -e "GRANT ALL PRIVILEGES ON \`${db_name}\`.* TO '${db_user}'@'${server01_private_ip}'; FLUSH PRIVILEGES;"

  # Recarrega MariaDB
  - systemctl restart mariadb 

  # Reinicia o SSH para aplicar porta 2222
  - systemctl restart ssh