#cloud-config
package_update: true
package_upgrade: true
timezone: "America/Sao_Paulo"

packages:
  - git
  - nginx
  - php-fpm
  - php-mysql
  - php-cli
  - unzip
  - curl
  - mariadb-client
  - certbot
  - python3-certbot-nginx

write_files:
  # SSH - Altera a porta de 22 para 2222
  - path: /etc/ssh/sshd_config.d/port-override.conf
    permissions: "0644"
    content: |
      Port 2222
      PasswordAuthentication no
      PermitRootLogin no

  # Nginx - Configuracao para o Crud
  - path: /etc/nginx/sites-available/default
    permissions: "0644"
    content: |
      server {
        listen 80;
        listen [::]:80;

        root /var/www/html/sistema;
        index index.php index.html index.htm;

        server_name ${server01_domain};

        location / {
          try_files $uri $uri/ =404;
        }

        location ~ \.php$ {
          include snippets/fastcgi-php.conf;
          fastcgi_pass unix:/run/php/php8.2-fpm.sock;
        }  
  
        location ~ /\.ht {
          deny all;
        }
      }

runcmd:
  # Download do sistema CRUD
  - curl -L -o /var/www/html/repo.zip https://github.com/ferpaesdias/Meu_PI_na_Nuvem/archive/refs/heads/main.zip
  - cd /var/www/html
  - unzip -q repo.zip "Meu_PI_na_Nuvem-main/sistema/*"
  - mv Meu_PI_na_Nuvem-main/sistema ./sistema
  - rm -rf Meu_PI_na_Nuvem-main repo.zip
  - chown -R www-data:www-data /var/www/html/sistema
  - chmod -R 755 /var/www/html/sistema

  # Reinicia servicos instalados
  - systemctl enable --now php-fpm || systemctl enable --now php8.2-fpm
  - nginx -t && systemctl reload nginx
  - systemctl restart ssh

  # Lets Encrypt
  - certbot --nginx -d ${server01_domain} --non-interactive --agree-tos -m ${letsencrypt_email} --redirect || true

  # Reiniciar Nginx apos certbot
  - nginx -t && systemctl reload nginx